# Generated by Django 5.2.4 on 2025-07-07 09:36

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.apps import apps


def create_groups(apps, schema_editor):
    """
    Créer les groupes Coach et Client avec leurs permissions
    """
    
    # Créer les groupes
    coach_group, created = Group.objects.get_or_create(name='Coach')
    client_group, created = Group.objects.get_or_create(name='Client')
    
    # Définir les permissions pour chaque groupe
    
    
    print("Groupes créés : Coach et Client")
    
def delete_groups(apps, schema_editor):
    """
    Supprimer les groupes (pour rollback)
    """
    Group.objects.filter(name__in=['Coach' ,'Client']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups)
    ]
