# Generated by Django 5.2.4 on 2025-07-08 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250707_1136'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(help_text='Note privée du coach sur ce client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_recues', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_donnees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note sur client',
                'verbose_name_plural': 'Notes sur clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
