# Generated by Django 5.2.4 on 2025-07-04 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_début', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('objet', models.TextField(help_text="Décrivez l'objet de votre séance")),
                ('statut', models.CharField(choices=[('reservee', 'Réservée'), ('confirmee', 'Confirmée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='reservee', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['date', 'heure_début'],
            },
        ),
    ]
