# Generated by Django 5.2.4 on 2025-07-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='notes_coach',
            field=models.TextField(blank=True, help_text='Notes privées du coach (non visibles par le client)', null=True),
        ),
    ]
